/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica.screens.paciente;

import br.edu.imepac.clinica.daos.PacienteDao;
import br.edu.imepac.clinica.entidades.Paciente;
import javax.swing.JOptionPane;

/**
 *
 * @author ypth
 */
public class PacienteUpdate extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PacienteUpdate.class.getName());

    
    private Paciente pacienteDataForm; 
    
    
    public PacienteUpdate(String cpf) {
        initComponents();
        setLocationRelativeTo(null); // centraliza
        loadDataInForm(cpf);
    }
    
     // guarda o paciente carregado do banco
    private void loadDataInForm(String cpf) {
        PacienteDao pacienteDao = new PacienteDao();
        this.pacienteDataForm = pacienteDao.buscarPorCpf(cpf);   // usa o DAO

        if (this.pacienteDataForm == null) {
            JOptionPane.showMessageDialog(this,
                    "Registro inválido para atualização!",
                    "Status da operação",
                    JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return;
        }

        nomeField.setText(this.pacienteDataForm.getNome());
        cpfFild.setText(this.pacienteDataForm.getCpf());
        cpfFild.setEditable(false); // CPF é chave do update
        convenioField.setText(String.valueOf(this.pacienteDataForm.getN_convenio()));
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cpfFild = new javax.swing.JTextField();
        salvarBtn = new javax.swing.JButton();
        LimparBtn = new javax.swing.JButton();
        fecharBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        convenioField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("Nome");

        nomeField.addActionListener(this::nomeFieldActionPerformed);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("CPF");

        cpfFild.addActionListener(this::cpfFildActionPerformed);

        salvarBtn.setText("Salvar");
        salvarBtn.addActionListener(this::salvarBtnActionPerformed);

        LimparBtn.setText("Limpar campos");
        LimparBtn.addActionListener(this::LimparBtnActionPerformed);

        fecharBtn.setText("Fechar");
        fecharBtn.addActionListener(this::fecharBtnActionPerformed);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Labels em negrito indicam campos obrigatórios e devem ser preenchidos");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Nº convênio");

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Atualizar Paciente");

        convenioField.addActionListener(this::convenioFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpfFild, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(convenioField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LimparBtn)
                        .addGap(45, 45, 45)
                        .addComponent(salvarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(fecharBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(3, 3, 3)
                .addComponent(cpfFild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convenioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBtn)
                    .addComponent(LimparBtn)
                    .addComponent(fecharBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed

        if (nomeField.getText().isBlank() ||
            cpfFild.getText().isBlank() ||
            convenioField.getText().isBlank()) {

            JOptionPane.showMessageDialog(this,
                    "Campos obrigatórios devem ser preenchidos!",
                    "Status da operação",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int nConvenio = Integer.parseInt(convenioField.getText());

        // monta objeto Paciente com os novos dados
        Paciente paciente = new Paciente(
                nomeField.getText(),
                cpfFild.getText(),   // mesmo CPF (WHERE cpf = ?)
                nConvenio
        );

        PacienteDao pacienteDao = new PacienteDao();
        boolean status = pacienteDao.atualizar(paciente);

        if (status) {
            JOptionPane.showMessageDialog(this,
                    "Paciente atualizado com sucesso!",
                    "Status da operação",
                    JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar paciente - contate o administrador!",
                    "Status da operação",
                    JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_salvarBtnActionPerformed

    private void LimparBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_LimparBtnActionPerformed

    private void fecharBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_fecharBtnActionPerformed

    private void cpfFildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFildActionPerformed

    private void convenioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convenioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convenioFieldActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LimparBtn;
    private javax.swing.JTextField convenioField;
    private javax.swing.JTextField cpfFild;
    private javax.swing.JButton fecharBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nomeField;
    private javax.swing.JButton salvarBtn;
    // End of variables declaration//GEN-END:variables
}
